import * as API from '.';

export default {
  deviceQueryByPage: (params) => API.GET('/operation/v1/device/queryByPage', params), // 设备管理-库存管理-设备库存-分页查询
  deviceAdd: (params) => API.POST('/operation/v1/device/add', params), // 设备管理-库存管理-设备库存-新增设备
  deviceQueryById: (params) => API.GET('/operation/v1/device/queryById', params), // 设备管理-库存管理-设备库存-编辑前的查询
  deviceUpdate: (params) => API.POST('/operation/v1/device/update', params), // 设备管理-库存管理-设备库存-修改设备
  deviceDelete: (params) => API.POST('/operation/v1/device/delete', params), // 设备管理-库存管理-设备库存-删除设备
  queryAllDeviceModel: (params) => API.GET('/operation/v1/device/queryAllDeviceModel', params), // 设备管理-库存管理-设备库存-查询所有设备型号/类型
  finishAllAgent: (params) => API.GET('/operation/v1/deviceOutput/finishAllAgent', params), // operation/v1/deviceActivation/queryByPage
  finishAllPrivilegeType: (params) => API.GET('/operation/v1/deviceOutput/finishAllPrivilegeType', params),
  deviceActivationQueryByPage: (params) => API.GET('/operation/v1/deviceActivation/queryByPage', params),
  deviceActivationUpdate: (params) => API.POST('/operation/v1/deviceActivation/update', params),
  deviceInputQueryByPage: (params) => API.GET('/operation/v1/deviceInput/queryByPage', params),
  deviceInputAdd: (params) => API.POST('/operation/v1/deviceInput/add', params),
  queryInputPage: (params) => API.POST('/operation/v1/deviceDetail/queryInputPage', params),
  queryOutputPage: (params) => API.GET('/operation/v1/deviceDetail/queryOutputPage', params),
  deviceDetailUpdate: (params) => API.POST('/operation/v1/deviceDetail/update', params),
  deviceDetailDelete: (params) => API.POST('/operation/v1/deviceDetail/delete', params), // 设备管理-库存管理-入库明细-删除入库
  deviceOutputAdd: (params) => API.POST('/operation/v1/deviceOutput/add', params),
  deviceOutputQueryByPage: (params) => API.GET('/operation/v1/deviceOutput/queryByPage', params),
  deviceOutputQueryById: (params) => API.GET('/operation/v1/deviceOutput/queryById', params),
  distribute: (params) => API.POST('/operation/v1/deviceOutput/distribute', params),
  reject: (params) => API.GET('/operation/v1/deviceOutput/reject', params),
  finishOutput: (params) => API.POST('/operation/v1/deviceOutput/finishOutput', params),
  finishOutputInfo: (params) => API.GET('/operation/v1/deviceOutput/finishOutputInfo', params), // 设备管理-库存管理-出库管理-查看发货信息
  queryUsing: (params) => API.GET('/operation/v1/deviceData/queryUsing', params), // 设备统计-查询各个设备正在使用的数量
  queryAllProvince: (params) => API.GET('/operation/v1/deviceData/queryAllProvince', params), // 设备统计-查询所有省份正在使用的数量
  queryRegion: (params) => API.GET('/operation/v1/deviceData/queryRegion', params),
  queryRegionTrade: (params) => API.GET('/operation/v1/deviceData/queryRegionTrade', params),
  queryMcc: (params) => API.GET('/operation/v1/deviceData/queryMcc', params),
  queryMccTrade: (params) => API.GET('/operation/v1/deviceData/queryMccTrade', params),
  queryDetail: (params) => API.GET('/operation/v1/deviceData/queryDetail', params),
  queryProcessLife: (params) => API.GET('/operation/v1/deviceData/queryProcessLife', params),
  deviceDataQueryByPage: (params) => API.GET('/operation/v1/deviceData/queryByPage', params),
  deviceMerchantQueryByPage: (params) => API.GET('/operation/v1/deviceMerchant/queryByPage', params), // 设备使用列表-分页查询
  unbind: (params) => API.POST('/operation/v1/deviceMerchant/unbind', params), // 设备使用列表-解绑
  unfreeze: (params) => API.POST('/operation/v1/deviceMerchant/unfreeze', params), // 设备使用列表-恢复可用
  deviceMaintainQueryByPage: (params) => API.GET('/operation/v1/deviceMaintain/queryByPage', params), // 设备维修-分页查询
  deviceMaintainQueryById: (params) => API.GET('/operation/v1/deviceMaintain/queryById', params), // 设备维修-通过ID查询
  auditPass: (params) => API.POST('/operation/v1/deviceMaintain/auditPass', params),
  auditReject: (params) => API.POST('/operation/v1/deviceMaintain/auditReject', params),
  receive: (params) => API.POST('/operation/v1/deviceMaintain/receive', params),
  saveMoney: (params) => API.POST('/operation/v1/deviceMaintain/saveMoney', params),
  send: (params) => API.POST('/operation/v1/deviceMaintain/send', params),
  deviceMallQueryByPage: (params) => API.GET('/operation/v1/deviceMall/queryByPage', params),
  deviceMallAdd: (params) => API.POST('/operation/v1/deviceMall/add', params),
  selectById: (params) => API.GET('/operation/v1/deviceMall/selectById', params), // 设备商城管理-根据主键查询
  deviceMallUpdate: (params) => API.POST('/operation/v1/deviceMall/update', params),
  deviceMallDelete: (params) => API.POST('/operation/v1/deviceMall/delete', params),
  on: (params) => API.POST('/operation/v1/deviceMall/on', params),
  off: (params) => API.POST('/operation/v1/deviceMall/off', params),
  queryAllOperation: () => API.GET('/operation/v1/advertPrivilege/queryAllOperation') // 查询所有运营人员
};
